# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 100  
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend
              topologyKey: "kubernetes.io/hostname"
      # Init container for database migrations
      initContainers:
        - name: db-migrate
          image: gcr.io/ucsf-medical-education-app/github.com/frozenstove/boost-socratic-backend:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
            - name: CHROMA_DB_URL
              value: "http://chroma-chromadb:8000"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: token
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running database migrations..."
              npm run db:generate
              npm run db:migrate:deploy
              echo "Migrations completed successfully"
      containers:
        - name: backend
          image: gcr.io/ucsf-medical-education-app/github.com/frozenstove/boost-socratic-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          readinessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
            - name: CHROMA_DB_URL
              value: "http://chroma-chromadb:8000"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: token
